# Generated by Django 4.2.3 on 2023-07-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakage',
            options={'verbose_name': 'Характер отказа', 'verbose_name_plural': 'Характер отказа'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-discharge_date'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-breakage_date'], 'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='drivingaxle',
            options={'verbose_name': 'Модель ведущего моста', 'verbose_name_plural': 'Модели ведущего моста'},
        ),
        migrations.AlterModelOptions(
            name='engine',
            options={'verbose_name': 'Модель двигателя', 'verbose_name_plural': 'Модели двигателя'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-maintenance_date'], 'verbose_name': 'Техническое обслуживание', 'verbose_name_plural': 'Техническое обслуживание'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetype',
            options={'verbose_name': 'Вид ТО', 'verbose_name_plural': 'Виды ТО'},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'verbose_name': 'Способ восстановления', 'verbose_name_plural': 'Способы восстановления'},
        ),
        migrations.AlterModelOptions(
            name='servicecompany',
            options={'verbose_name': 'Сервисная компания', 'verbose_name_plural': 'Сервисные компании'},
        ),
        migrations.AlterModelOptions(
            name='steeringaxle',
            options={'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Модели управляемого моста'},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={'verbose_name': 'Модель трансмиссии', 'verbose_name_plural': 'Модели трансмиссии'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Модель техники', 'verbose_name_plural': 'Модели техники'},
        ),
        migrations.AlterField(
            model_name='car',
            name='vehicle_configuration',
            field=models.CharField(max_length=512, verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='down_time',
            field=models.IntegerField(verbose_name='Время простоя'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='order_date',
            field=models.DateField(verbose_name='Дата заказ-наряда'),
        ),
    ]
