# Generated by Django 4.2.3 on 2023-08-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_breakage_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Модель погрузчика', 'verbose_name_plural': 'Модели погрузчика'},
        ),
    ]
