# Generated by Django 4.2.3 on 2023-08-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_login_data_servicecompany_login_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='spares',
            field=models.CharField(blank=True, max_length=256, verbose_name='Используемые запасные части'),
        ),
        migrations.AlterField(
            model_name='servicecompany',
            name='login_nickname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Логин для входа'),
        ),
    ]
