# Generated by Django 4.2.3 on 2023-08-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_complaint_spares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driving_axle_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering_axle_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='Зав. № трансмиссии'),
        ),
    ]
