# Generated by Django 4.2.3 on 2023-08-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_maintenance_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakage',
            options={'verbose_name': 'Узел отказа', 'verbose_name_plural': 'Узлы отказа'},
        ),
    ]
