# Generated by Django 4.2.3 on 2023-08-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_maintenancetype_options_alter_breakage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecompany',
            name='login_nickname',
            field=models.CharField(max_length=64, unique=True, verbose_name='Логин для входа'),
        ),
    ]
